# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1411, 448)
        Form.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.HeadBar = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HeadBar.sizePolicy().hasHeightForWidth())
        self.HeadBar.setSizePolicy(sizePolicy)
        self.HeadBar.setMinimumSize(QtCore.QSize(0, 40))
        self.HeadBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.HeadBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HeadBar.setObjectName("HeadBar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.HeadBar)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.HeadBar)
        self.widget.setObjectName("widget")
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.HeadBar)
        self.widget_2.setMaximumSize(QtCore.QSize(301, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toolButton = QtWidgets.QToolButton(self.widget_2)
        self.toolButton.setMinimumSize(QtCore.QSize(35, 0))
        self.toolButton.setMaximumSize(QtCore.QSize(35, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icon/qRef.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(48, 48))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_5.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_2.setMinimumSize(QtCore.QSize(35, 0))
        self.toolButton_2.setMaximumSize(QtCore.QSize(35, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Icon/masterdata.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(64, 64))
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_5.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Icon/chat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_5.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_5.addWidget(self.toolButton_4, 0, 3, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_5.addWidget(self.toolButton_5, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.HeadBar, 0, 1, 1, 2)
        self.MenuBar = QtWidgets.QWidget(Form)
        self.MenuBar.setMinimumSize(QtCore.QSize(30, 0))
        self.MenuBar.setMaximumSize(QtCore.QSize(221, 16777215))
        self.MenuBar.setObjectName("MenuBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MenuBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftBar = QtWidgets.QWidget(self.MenuBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftBar.sizePolicy().hasHeightForWidth())
        self.LeftBar.setSizePolicy(sizePolicy)
        self.LeftBar.setMinimumSize(QtCore.QSize(30, 0))
        self.LeftBar.setMaximumSize(QtCore.QSize(60, 16777215))
        self.LeftBar.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.LeftBar.setObjectName("LeftBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LeftBar)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DASHBOARD = QtWidgets.QToolButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DASHBOARD.sizePolicy().hasHeightForWidth())
        self.DASHBOARD.setSizePolicy(sizePolicy)
        self.DASHBOARD.setMinimumSize(QtCore.QSize(0, 50))
        self.DASHBOARD.setMaximumSize(QtCore.QSize(16777215, 50))
        self.DASHBOARD.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Icon/dashboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DASHBOARD.setIcon(icon3)
        self.DASHBOARD.setIconSize(QtCore.QSize(64, 64))
        self.DASHBOARD.setAutoRaise(True)
        self.DASHBOARD.setObjectName("DASHBOARD")
        self.verticalLayout.addWidget(self.DASHBOARD)
        self.COMPANIES = QtWidgets.QToolButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.COMPANIES.sizePolicy().hasHeightForWidth())
        self.COMPANIES.setSizePolicy(sizePolicy)
        self.COMPANIES.setMinimumSize(QtCore.QSize(0, 50))
        self.COMPANIES.setMaximumSize(QtCore.QSize(16777215, 50))
        self.COMPANIES.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Icon/company.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.COMPANIES.setIcon(icon4)
        self.COMPANIES.setIconSize(QtCore.QSize(64, 64))
        self.COMPANIES.setAutoRaise(True)
        self.COMPANIES.setObjectName("COMPANIES")
        self.verticalLayout.addWidget(self.COMPANIES)
        self.LLP = QtWidgets.QToolButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LLP.sizePolicy().hasHeightForWidth())
        self.LLP.setSizePolicy(sizePolicy)
        self.LLP.setMinimumSize(QtCore.QSize(0, 50))
        self.LLP.setMaximumSize(QtCore.QSize(16777215, 50))
        self.LLP.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Icon/llp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LLP.setIcon(icon5)
        self.LLP.setIconSize(QtCore.QSize(64, 64))
        self.LLP.setAutoRaise(True)
        self.LLP.setObjectName("LLP")
        self.verticalLayout.addWidget(self.LLP)
        self.ACCOUNTS = QtWidgets.QToolButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ACCOUNTS.sizePolicy().hasHeightForWidth())
        self.ACCOUNTS.setSizePolicy(sizePolicy)
        self.ACCOUNTS.setMinimumSize(QtCore.QSize(0, 50))
        self.ACCOUNTS.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ACCOUNTS.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Icon/accounting.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ACCOUNTS.setIcon(icon6)
        self.ACCOUNTS.setIconSize(QtCore.QSize(64, 64))
        self.ACCOUNTS.setAutoRaise(True)
        self.ACCOUNTS.setObjectName("ACCOUNTS")
        self.verticalLayout.addWidget(self.ACCOUNTS)
        self.TOOLS = QtWidgets.QToolButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TOOLS.sizePolicy().hasHeightForWidth())
        self.TOOLS.setSizePolicy(sizePolicy)
        self.TOOLS.setMinimumSize(QtCore.QSize(0, 50))
        self.TOOLS.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TOOLS.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../Icon/tools.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TOOLS.setIcon(icon7)
        self.TOOLS.setIconSize(QtCore.QSize(64, 64))
        self.TOOLS.setAutoRaise(True)
        self.TOOLS.setObjectName("TOOLS")
        self.verticalLayout.addWidget(self.TOOLS)
        self.ADMIN = QtWidgets.QToolButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ADMIN.sizePolicy().hasHeightForWidth())
        self.ADMIN.setSizePolicy(sizePolicy)
        self.ADMIN.setMinimumSize(QtCore.QSize(0, 50))
        self.ADMIN.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ADMIN.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../Icon/admin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ADMIN.setIcon(icon8)
        self.ADMIN.setIconSize(QtCore.QSize(64, 64))
        self.ADMIN.setAutoRaise(True)
        self.ADMIN.setObjectName("ADMIN")
        self.verticalLayout.addWidget(self.ADMIN)
        self.horizontalLayout.addWidget(self.LeftBar)
        self.ExtendedMenu = QtWidgets.QWidget(self.MenuBar)
        self.ExtendedMenu.setMaximumSize(QtCore.QSize(171, 16777215))
        self.ExtendedMenu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ExtendedMenu.setObjectName("ExtendedMenu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ExtendedMenu)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MenuTitle = QtWidgets.QLabel(self.ExtendedMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenuTitle.sizePolicy().hasHeightForWidth())
        self.MenuTitle.setSizePolicy(sizePolicy)
        self.MenuTitle.setMinimumSize(QtCore.QSize(0, 40))
        self.MenuTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.MenuTitle.setFont(font)
        self.MenuTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.MenuTitle.setObjectName("MenuTitle")
        self.gridLayout_3.addWidget(self.MenuTitle, 0, 0, 1, 1)
        self.ExtendedMenuItems = QtWidgets.QScrollArea(self.ExtendedMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.ExtendedMenuItems.setFont(font)
        self.ExtendedMenuItems.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ExtendedMenuItems.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ExtendedMenuItems.setLineWidth(0)
        self.ExtendedMenuItems.setWidgetResizable(True)
        self.ExtendedMenuItems.setObjectName("ExtendedMenuItems")
        self.MenuLayout = QtWidgets.QWidget()
        self.MenuLayout.setGeometry(QtCore.QRect(0, 0, 161, 408))
        self.MenuLayout.setObjectName("MenuLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MenuLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButton_6 = QtWidgets.QToolButton(self.MenuLayout)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.toolButton_6.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../Icon/activities.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon9)
        self.toolButton_6.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.verticalLayout_2.addWidget(self.toolButton_6)
        self.ExtendedMenuItems.setWidget(self.MenuLayout)
        self.gridLayout_3.addWidget(self.ExtendedMenuItems, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.ExtendedMenu)
        self.gridLayout.addWidget(self.MenuBar, 0, 0, 2, 1)
        self.RightBar = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightBar.sizePolicy().hasHeightForWidth())
        self.RightBar.setSizePolicy(sizePolicy)
        self.RightBar.setMinimumSize(QtCore.QSize(0, 0))
        self.RightBar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.RightBar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.RightBar.setObjectName("RightBar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RightBar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.WidgetTitle = QtWidgets.QLabel(self.RightBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetTitle.sizePolicy().hasHeightForWidth())
        self.WidgetTitle.setSizePolicy(sizePolicy)
        self.WidgetTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.WidgetTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.WidgetTitle.setFont(font)
        self.WidgetTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.WidgetTitle.setObjectName("WidgetTitle")
        self.gridLayout_2.addWidget(self.WidgetTitle, 0, 0, 1, 1)
        self.WidgetWindow = QtWidgets.QWidget(self.RightBar)
        self.WidgetWindow.setObjectName("WidgetWindow")
        self.gridLayout_2.addWidget(self.WidgetWindow, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.RightBar, 1, 2, 1, 1)
        self.ManWindow = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManWindow.sizePolicy().hasHeightForWidth())
        self.ManWindow.setSizePolicy(sizePolicy)
        self.ManWindow.setObjectName("ManWindow")
        self.gridLayout.addWidget(self.ManWindow, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton.setText(_translate("Form", "..."))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.toolButton_3.setText(_translate("Form", "..."))
        self.toolButton_4.setText(_translate("Form", "..."))
        self.toolButton_5.setText(_translate("Form", "..."))
        self.DASHBOARD.setText(_translate("Form", "..."))
        self.COMPANIES.setText(_translate("Form", "..."))
        self.COMPANIES.setShortcut(_translate("Form", "Ctrl+R"))
        self.LLP.setText(_translate("Form", "..."))
        self.ACCOUNTS.setText(_translate("Form", "..."))
        self.TOOLS.setText(_translate("Form", "..."))
        self.ADMIN.setText(_translate("Form", "..."))
        self.MenuTitle.setText(_translate("Form", "Chat Room"))
        self.toolButton_6.setText(_translate("Form", "Add Company"))
        self.WidgetTitle.setText(_translate("Form", "Chat Room"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
