
client_config_backend: settings
client_config:
  client_id: 168623733207-28920ec40pf76ri6uaj37sos4p0j9sdp.apps.googleusercontent.com
  client_secret: eA8W9dVUC4yy5n2Vz6N42KGy

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.metadata
